select * from [dbo].[tmplstGerOper_imp] (nolock)

select
sNumProc  as 'Numero do Processo',
sProd  as Produto,
sCli  as Cliente,
sFamiCli  as 'Família do Cliente',
sConsignee  as Consignee,
sEmpExt  as 'Empresa no Exterior',
sCiaAeria  as 'Cia Aérea / Armador',
sAgente  as Agente,
sPurOrder  as 'Purcharse Order',
sInvoice  as Invoice,
sRefCli  as 'Ref. Cliente',
sModalidade  as Modalidade,
sNegociacao  as Negociação,
sEscopo  as Escopo,
sOferta  as Oferta,
sIncoterm  as Incoterm,
sRespOpe  as 'Responsável Operacional',
dtAbertura  as 'Dt de Abertura',
sPaisCol  as 'País Coleta / Origem',
sCidadeColeta  as 'Cidade Coleta',
sOrigEmb  as 'Origem Embarque / Porto Origem',
sDestMawb  as 'Destino MAWB / Porto Destino',
sDestFinal  as 'Destino Final',
dtPrevDisp  as 'Prev. Disponibilidade',
dtEnvInstEmb  as 'Envio Inst embarque',
dtConfColeta  as 'Confirmação de Coleta',
dtRecebCarga  as 'Recebimento da Carga',
dtAutCarga  as 'Autorização da Carga',
dtAprovHawb  as 'Aprovação HAWB',
sMaster  as 'Master',
dtEmisMaster  as 'Emisao Master',
sHouse  as House,
dtEmisHouse  as 'Emisao House',
sNavio  as Navio,
dtPrevSaida  as 'Prev. Saida / ETD',
dtConfSaida  as 'Conf.Saida / Conf. Embarque',
dtPrevCheg  as 'Prev. Chegada / ETA Booking',
dtConfCheg  as 'Conf. Chegada / Conf. Atracação' ,
sQtdVol  as 'Qtd Volumes',
iTeus  as Teus,
dPesoBruto  as 'Peso Bruto',
dPesoTax  as 'Peso Taxado',
dM3  as 'M³ / CBM',
dtDesova  as 'Dt Desova',
sCEMaster  as 'CE Master',
sCEHouse  as 'CE House',
dtCEHouse  as 'Dt CE House',
dtMBLLiberadoEm  as 'MBL Liberado em',
dtHBLLiberadoEm  as 'HBL Liberado em',
dtEntregueEm  as 'Entregue em',
dTotalCompra  as 'Total Compra',
dTotalVenda  as 'Total Venda',
dMCPerc  as 'MC %',
dMCValor  as 'MC valor',
sMoedaVendaOrig  as 'Moeda Venda Origem',
dVlVendaOrig  as 'VL Venda Origem',
sMoedaFrete  as 'Moeda Frete',
dVlFreteComp  as 'VL Frete Compra',
dVlFrete  as 'VL Frete',
sMoedaVendaDest  as 'Moeda Venda Destino',
dVlVendaDest  as 'VL Venda Destino',
dVlLucroReal  as 'VL Lucro Real',
dLucroOpe  as 'Lucro Operacional',
dLucroEst  as 'Lucro Estimado',
dVarCamb  as 'Variação Cambial',
sStatus  as 'Status',
dtEnvioFat  as 'Dt Envio Fatura',
dtEmisFat  as 'Dt Emissão Fatura',
sDebCred  as 'Debit/Credit',
dDiverg  as 'Divergencia',
dtEncOpe  as 'Encerramento Operacional',
sMotCancel  as 'Motivo Cancelamento',
sDtAlt  as 'Data de Alteração',
sInlandMoeda  as 'Inland Moeda',
dInlandValor  as 'Inland Valor',
sJustPreju  as 'Justificativa Prejuizo',
dVlAproxFat  as 'Vl. Aprox. da Fatura',
sTerminalDesc  as 'Terminal de Descarga',
dVlTotItensVenda  as 'Valor total de intens a venda',
dProfitPgAg as 'Profit Pg Ag',
sMoedaProfitAg as 'Moeda Profit Ag',
dtPrevAtrac as 'Dt Prev Atrac'

from tmplstGerOper_imp